const SITES = [
  // SOCIAL MEDIA
  { n:'Facebook', u:'https://facebook.com/{u}', c:'Social', e:'status' },
  { n:'Instagram', u:'https://instagram.com/{u}', c:'Social', e:'status' },
  { n:'Twitter', u:'https://twitter.com/{u}', c:'Social', e:'status' },
  { n:'LinkedIn', u:'https://linkedin.com/in/{u}', c:'Social', e:'status' },
  { n:'TikTok', u:'https://tiktok.com/@{u}', c:'Social', e:'status' },
  { n:'Snapchat', u:'https://snapchat.com/add/{u}', c:'Social', e:'status' },
  { n:'Pinterest', u:'https://pinterest.com/{u}', c:'Social', e:'status' },
  { n:'YouTube', u:'https://youtube.com/@{u}', c:'Social', e:'status' },
  { n:'Reddit', u:'https://reddit.com/user/{u}', c:'Social', e:'status' },
  { n:'Tumblr', u:'https://{u}.tumblr.com', c:'Social', e:'status' },
  { n:'Flickr', u:'https://flickr.com/people/{u}', c:'Social', e:'status' },
  { n:'Myspace', u:'https://myspace.com/{u}', c:'Social', e:'status' },
  { n:'Patreon', u:'https://patreon.com/{u}', c:'Social', e:'status' },
  { n:'Medium', u:'https://medium.com/@{u}', c:'Social', e:'status' },
  { n:'Behance', u:'https://behance.net/{u}', c:'Social', e:'status' },
  { n:'Dribbble', u:'https://dribbble.com/{u}', c:'Social', e:'status' },
  { n:'AngelList', u:'https://angel.co/u/{u}', c:'Social', e:'status' },
  { n:'Crunchbase', u:'https://crunchbase.com/person/{u}', c:'Social', e:'status' },
  { n:'About.me', u:'https://about.me/{u}', c:'Social', e:'status' },
  { n:'Keybase', u:'https://keybase.io/{u}', c:'Social', e:'status' },
  { n:'Linktree', u:'https://linktr.ee/{u}', c:'Social', e:'status' },
  { n:'Carrd', u:'https://{u}.carrd.co', c:'Social', e:'status' },
  { n:'Bio.link', u:'https://bio.link/{u}', c:'Social', e:'status' },
  { n:'Beacons', u:'https://beacons.ai/{u}', c:'Social', e:'status' },
  { n:'Mastodon.social', u:'https://mastodon.social/@{u}', c:'Social', e:'status' },
  { n:'Threads', u:'https://threads.net/@{u}', c:'Social', e:'status' },
  { n:'Bluesky', u:'https://bsky.app/profile/{u}', c:'Social', e:'status' },
  { n:'Weibo', u:'https://weibo.com/{u}', c:'Social', e:'status' },
  { n:'VK', u:'https://vk.com/{u}', c:'Social', e:'status' },
  { n:'Odnoklassniki', u:'https://ok.ru/{u}', c:'Social', e:'status' },
  { n:'Telegram', u:'https://t.me/{u}', c:'Social', e:'status' },
  { n:'WhatsApp', u:'https://wa.me/{u}', c:'Social', e:'status' },
  { n:'Discord', u:'https://discord.com/users/{u}', c:'Social', e:'status' },
  { n:'Twitch', u:'https://twitch.tv/{u}', c:'Social', e:'status' },
  { n:'Periscope', u:'https://periscope.tv/{u}', c:'Social', e:'status' },
  { n:'Mixer', u:'https://mixer.com/{u}', c:'Social', e:'status' },
  { n:'DLive', u:'https://dlive.tv/{u}', c:'Social', e:'status' },
  { n:'Trovo', u:'https://trovo.live/{u}', c:'Social', e:'status' },
  { n:'Rumble', u:'https://rumble.com/user/{u}', c:'Social', e:'status' },
  { n:'Odysee', u:'https://odysee.com/@{u}', c:'Social', e:'status' },
  { n:'PeerTube', u:'https://peertube.tv/accounts/{u}', c:'Social', e:'status' },

  // CODING
  { n:'GitHub', u:'https://github.com/{u}', c:'Coding', e:'status' },
  { n:'GitLab', u:'https://gitlab.com/{u}', c:'Coding', e:'status' },
  { n:'Bitbucket', u:'https://bitbucket.org/{u}', c:'Coding', e:'status' },
  { n:'Stack Overflow', u:'https://stackoverflow.com/users/*/{u}', c:'Coding', e:'status' },
  { n:'CodePen', u:'https://codepen.io/{u}', c:'Coding', e:'status' },
  { n:'Replit', u:'https://replit.com/@{u}', c:'Coding', e:'status' },
  { n:'HackerRank', u:'https://hackerrank.com/profile/{u}', c:'Coding', e:'status' },
  { n:'LeetCode', u:'https://leetcode.com/{u}', c:'Coding', e:'status' },
  { n:'Codeforces', u:'https://codeforces.com/profile/{u}', c:'Coding', e:'status' },
  { n:'TopCoder', u:'https://topcoder.com/members/{u}', c:'Coding', e:'status' },
  { n:'Kaggle', u:'https://kaggle.com/{u}', c:'Coding', e:'status' },
  { n:'Dev.to', u:'https://dev.to/{u}', c:'Coding', e:'status' },
  { n:'HackerOne', u:'https://hackerone.com/{u}', c:'Coding', e:'status' },
  { n:'Bugcrowd', u:'https://bugcrowd.com/{u}', c:'Coding', e:'status' },
  { n:'SourceForge', u:'https://sourceforge.net/u/{u}', c:'Coding', e:'status' },
  { n:'NPM', u:'https://npmjs.com/~{u}', c:'Coding', e:'status' },
  { n:'PyPI', u:'https://pypi.org/user/{u}', c:'Coding', e:'status' },
  { n:'RubyGems', u:'https://rubygems.org/profiles/{u}', c:'Coding', e:'status' },
  { n:'NuGet', u:'https://nuget.org/profiles/{u}', c:'Coding', e:'status' },
  { n:'Docker Hub', u:'https://hub.docker.com/u/{u}', c:'Coding', e:'status' },
  { n:'JSFiddle', u:'https://jsfiddle.net/user/{u}', c:'Coding', e:'status' },
  { n:'CodeSandbox', u:'https://codesandbox.io/u/{u}', c:'Coding', e:'status' },
  { n:'Glitch', u:'https://glitch.com/@{u}', c:'Coding', e:'status' },
  { n:'GitLab Pages', u:'https://{u}.gitlab.io', c:'Coding', e:'status' },
  { n:'Codewars', u:'https://codewars.com/users/{u}', c:'Coding', e:'status' },
  { n:'Exercism', u:'https://exercism.org/profiles/{u}', c:'Coding', e:'status' },
  { n:'GeeksforGeeks', u:'https://geeksforgeeks.org/user/{u}', c:'Coding', e:'status' },
  { n:'Medium (coding)', u:'https://{u}.medium.com', c:'Coding', e:'status' },
  { n:'Hashnode', u:'https://hashnode.com/@{u}', c:'Coding', e:'status' },

  // PROFESSIONAL
  { n:'Upwork', u:'https://upwork.com/freelancers/~{u}', c:'Professional', e:'status' },
  { n:'Fiverr', u:'https://fiverr.com/{u}', c:'Professional', e:'status' },
  { n:'Freelancer', u:'https://freelancer.com/u/{u}', c:'Professional', e:'status' },
  { n:'99designs', u:'https://99designs.com/profiles/{u}', c:'Professional', e:'status' },
  { n:'Toptal', u:'https://toptal.com/resume/{u}', c:'Professional', e:'status' },
  { n:'Guru', u:'https://guru.com/freelancers/{u}', c:'Professional', e:'status' },
  { n:'PeoplePerHour', u:'https://peopleperhour.com/freelancer/{u}', c:'Professional', e:'status' },
  { n:'Indeed', u:'https://indeed.com/r/{u}', c:'Professional', e:'status' },
  { n:'Glassdoor', u:'https://glassdoor.com/Overview/{u}', c:'Professional', e:'status' },
  { n:'Xing', u:'https://xing.com/profile/{u}', c:'Professional', e:'status' },
  { n:'ResearchGate', u:'https://researchgate.net/profile/{u}', c:'Professional', e:'status' },
  { n:'Academia.edu', u:'https://academia.edu/{u}', c:'Professional', e:'status' },
  { n:'ORCID', u:'https://orcid.org/{u}', c:'Professional', e:'status' },
  { n:'Google Scholar', u:'https://scholar.google.com/citations?user={u}', c:'Professional', e:'status' },
  { n:'SlideShare', u:'https://slideshare.net/{u}', c:'Professional', e:'status' },
  { n:'Scribd', u:'https://scribd.com/{u}', c:'Professional', e:'status' },
  { n:'Issuu', u:'https://issuu.com/{u}', c:'Professional', e:'status' },
  { n:'Contently', u:'https://{u}.contently.com', c:'Professional', e:'status' },
  { n:'Muck Rack', u:'https://muckrack.com/{u}', c:'Professional', e:'status' },
  { n:'PressReader', u:'https://pressreader.com/@{u}', c:'Professional', e:'status' },

  // GAMING
  { n:'Steam', u:'https://steamcommunity.com/id/{u}', c:'Gaming', e:'status' },
  { n:'Xbox Live', u:'https://xboxgamertag.com/search/{u}', c:'Gaming', e:'status' },
  { n:'PlayStation', u:'https://psnprofiles.com/{u}', c:'Gaming', e:'status' },
  { n:'Nintendo', u:'https://en-americas-support.nintendo.com/user/{u}', c:'Gaming', e:'status' },
  { n:'Epic Games', u:'https://epicgames.com/id/{u}', c:'Gaming', e:'status' },
  { n:'Battle.net', u:'https://battle.net/{u}', c:'Gaming', e:'status' },
  { n:'Riot Games', u:'https://riotgames.com/account/{u}', c:'Gaming', e:'status' },
  { n:'Roblox', u:'https://roblox.com/user/{u}', c:'Gaming', e:'status' },
  { n:'Minecraft', u:'https://namemc.com/profile/{u}', c:'Gaming', e:'status' },
  { n:'Chess.com', u:'https://chess.com/member/{u}', c:'Gaming', e:'status' },
  { n:'Lichess', u:'https://lichess.org/@/{u}', c:'Gaming', e:'status' },
  { n:'speedrun.com', u:'https://speedrun.com/users/{u}', c:'Gaming', e:'status' },
  { n:'Kongregate', u:'https://kongregate.com/accounts/{u}', c:'Gaming', e:'status' },
  { n:'Newgrounds', u:'https://newgrounds.com/{u}', c:'Gaming', e:'status' },
  { n:'Armor Games', u:'https://armorgames.com/user/{u}', c:'Gaming', e:'status' },
  { n:'Game Jolt', u:'https://gamejolt.com/@{u}', c:'Gaming', e:'status' },
  { n:'Itch.io', u:'https://{u}.itch.io', c:'Gaming', e:'status' },
  { n:'CurseForge', u:'https://curseforge.com/members/{u}', c:'Gaming', e:'status' },

  // FORUMS & COMMUNITIES
  { n:'Quora', u:'https://quora.com/profile/{u}', c:'Forums', e:'status' },
  { n:'Stack Exchange', u:'https://stackexchange.com/users/*/{u}', c:'Forums', e:'status' },
  { n:'Product Hunt', u:'https://producthunt.com/@{u}', c:'Forums', e:'status' },
  { n:'BuzzFeed', u:'https://buzzfeed.com/{u}', c:'Forums', e:'status' },
  { n:'Imgur', u:'https://imgur.com/user/{u}', c:'Forums', e:'status' },
  { n:'9GAG', u:'https://9gag.com/u/{u}', c:'Forums', e:'status' },
  { n:'Pixiv', u:'https://pixiv.net/users/{u}', c:'Forums', e:'status' },
  { n:'DeviantArt', u:'https://deviantart.com/{u}', c:'Forums', e:'status' },
  { n:'ArtStation', u:'https://artstation.com/{u}', c:'Forums', e:'status' },
  { n:'500px', u:'https://500px.com/{u}', c:'Forums', e:'status' },
  { n:'Unsplash', u:'https://unsplash.com/@{u}', c:'Forums', e:'status' },
  { n:'Giphy', u:'https://giphy.com/{u}', c:'Forums', e:'status' },
  { n:'Tenor', u:'https://tenor.com/users/{u}', c:'Forums', e:'status' },
  { n:'Wattpad', u:'https://wattpad.com/user/{u}', c:'Forums', e:'status' },
  { n:'FanFiction', u:'https://fanfiction.net/u/{u}', c:'Forums', e:'status' },
  { n:'Archive of Our Own', u:'https://archiveofourown.org/users/{u}', c:'Forums', e:'status' },
  { n:'Goodreads', u:'https://goodreads.com/{u}', c:'Forums', e:'status' },
  { n:'WordPress', u:'https://{u}.wordpress.com', c:'Forums', e:'status' },
  { n:'Blogger', u:'https://{u}.blogspot.com', c:'Forums', e:'status' },
  { n:'Wix', u:'https://{u}.wixsite.com', c:'Forums', e:'status' },
  { n:'Squarespace', u:'https://{u}.squarespace.com', c:'Forums', e:'status' },
  { n:'Webflow', u:'https://webflow.com/@{u}', c:'Forums', e:'status' },
  { n:'Notion', u:'https://{u}.notion.site', c:'Forums', e:'status' },
  { n:'Substack', u:'https://{u}.substack.com', c:'Forums', e:'status' },

  // SHOPPING
  { n:'Etsy', u:'https://etsy.com/shop/{u}', c:'Shopping', e:'status' },
  { n:'eBay', u:'https://ebay.com/usr/{u}', c:'Shopping', e:'status' },
  { n:'Amazon Seller', u:'https://amazon.com/sp/{u}', c:'Shopping', e:'status' },
  { n:'Wish', u:'https://wish.com/@{u}', c:'Shopping', e:'status' },
  { n:'Mercari', u:'https://mercari.com/u/{u}', c:'Shopping', e:'status' },
  { n:'Poshmark', u:'https://poshmark.com/closet/{u}', c:'Shopping', e:'status' },
  { n:'Depop', u:'https://depop.com/{u}', c:'Shopping', e:'status' },
  { n:'Vinted', u:'https://vinted.com/member/{u}', c:'Shopping', e:'status' },
  { n:'Grailed', u:'https://grailed.com/{u}', c:'Shopping', e:'status' },
  { n:'Reverb', u:'https://reverb.com/shop/{u}', c:'Shopping', e:'status' },
  { n:'Bandcamp', u:'https://bandcamp.com/{u}', c:'Shopping', e:'status' },
  { n:'Redbubble', u:'https://redbubble.com/people/{u}', c:'Shopping', e:'status' },
  { n:'Society6', u:'https://society6.com/{u}', c:'Shopping', e:'status' },
  { n:'Teespring', u:'https://teespring.com/stores/{u}', c:'Shopping', e:'status' },
  { n:'Gumroad', u:'https://gumroad.com/{u}', c:'Shopping', e:'status' },
  { n:'Lemon Squeezy', u:'https://{u}.lemonsqueezy.com', c:'Shopping', e:'status' },
  { n:'Shopify', u:'https://{u}.myshopify.com', c:'Shopping', e:'status' },
  { n:'BigCartel', u:'https://{u}.bigcartel.com', c:'Shopping', e:'status' },

  // MUSIC & VIDEO
  { n:'Spotify', u:'https://open.spotify.com/user/{u}', c:'Music', e:'status' },
  { n:'SoundCloud', u:'https://soundcloud.com/{u}', c:'Music', e:'status' },
  { n:'BandLab', u:'https://bandlab.com/{u}', c:'Music', e:'status' },
  { n:'Mixcloud', u:'https://mixcloud.com/{u}', c:'Music', e:'status' },
  { n:'Vimeo', u:'https://vimeo.com/{u}', c:'Music', e:'status' },
  { n:'Dailymotion', u:'https://dailymotion.com/{u}', c:'Music', e:'status' },
  { n:'IMDb', u:'https://imdb.com/user/ur{u}', c:'Music', e:'status' },
  { n:'Letterboxd', u:'https://letterboxd.com/{u}', c:'Music', e:'status' },
  { n:'Trakt', u:'https://trakt.tv/users/{u}', c:'Music', e:'status' },
  { n:'MyAnimeList', u:'https://myanimelist.net/profile/{u}', c:'Music', e:'status' },
  { n:'AniList', u:'https://anilist.co/user/{u}', c:'Music', e:'status' },
  { n:'Last.fm', u:'https://last.fm/user/{u}', c:'Music', e:'status' },
  { n:'Genius', u:'https://genius.com/{u}', c:'Music', e:'status' },
  { n:'Shazam', u:'https://shazam.com/artist/{u}', c:'Music', e:'status' },
  { n:'Tidal', u:'https://tidal.com/{u}', c:'Music', e:'status' },
  { n:'Apple Music', u:'https://music.apple.com/profile/{u}', c:'Music', e:'status' },
  { n:'Shutterstock', u:'https://shutterstock.com/g/{u}', c:'Music', e:'status' },

  // DATING
  { n:'Tinder', u:'https://tinder.com/@{u}', c:'Dating', e:'status' },
  { n:'Bumble', u:'https://bumble.com/profile/{u}', c:'Dating', e:'status' },
  { n:'Hinge', u:'https://hinge.co/profile/{u}', c:'Dating', e:'status' },
  { n:'OKCupid', u:'https://okcupid.com/profile/{u}', c:'Dating', e:'status' },
  { n:'Plenty of Fish', u:'https://pof.com/member/{u}', c:'Dating', e:'status' },
  { n:'Match.com', u:'https://match.com/profile/{u}', c:'Dating', e:'status' },
  { n:'Grindr', u:'https://grindr.com/profile/{u}', c:'Dating', e:'status' },
  { n:'Badoo', u:'https://badoo.com/en/{u}', c:'Dating', e:'status' },

  // CRYPTO / WEB3
  { n:'Etherscan', u:'https://etherscan.io/address/{u}', c:'Crypto', e:'status' },
  { n:'OpenSea', u:'https://opensea.io/{u}', c:'Crypto', e:'status' },
  { n:'Rarible', u:'https://rarible.com/user/{u}', c:'Crypto', e:'status' },
  { n:'Foundation', u:'https://foundation.app/@{u}', c:'Crypto', e:'status' },
  { n:'SuperRare', u:'https://superrare.com/{u}', c:'Crypto', e:'status' },
  { n:'Zora', u:'https://zora.co/@{u}', c:'Crypto', e:'status' },
  { n:'Coinbase', u:'https://coinbase.com/{u}', c:'Crypto', e:'status' },
  { n:'Binance', u:'https://binance.com/en/profile/{u}', c:'Crypto', e:'status' },
  { n:'Gitcoin', u:'https://gitcoin.co/{u}', c:'Crypto', e:'status' },

  // TRAVEL
  { n:'TripAdvisor', u:'https://tripadvisor.com/members/{u}', c:'Travel', e:'status' },
  { n:'Booking.com', u:'https://booking.com/profile/{u}', c:'Travel', e:'status' },
  { n:'Airbnb', u:'https://airbnb.com/users/show/{u}', c:'Travel', e:'status' },
  { n:'Couchsurfing', u:'https://couchsurfing.com/people/{u}', c:'Travel', e:'status' },
  { n:'Uber', u:'https://uber.com/u/{u}', c:'Travel', e:'status' },
  { n:'Lyft', u:'https://lyft.com/profile/{u}', c:'Travel', e:'status' },
  { n:'Waze', u:'https://waze.com/user/{u}', c:'Travel', e:'status' },
  { n:'Yelp', u:'https://yelp.com/user_details?userid={u}', c:'Travel', e:'status' },
  { n:'Foursquare', u:'https://foursquare.com/user/{u}', c:'Travel', e:'status' },

  // EDUCATION
  { n:'Coursera', u:'https://coursera.org/user/{u}', c:'Education', e:'status' },
  { n:'edX', u:'https://edx.org/user/{u}', c:'Education', e:'status' },
  { n:'Udemy', u:'https://udemy.com/user/{u}', c:'Education', e:'status' },
  { n:'Skillshare', u:'https://skillshare.com/en/profile/{u}', c:'Education', e:'status' },
  { n:'Duolingo', u:'https://duolingo.com/profile/{u}', c:'Education', e:'status' },
  { n:'Memrise', u:'https://memrise.com/user/{u}', c:'Education', e:'status' },
  { n:'Khan Academy', u:'https://khanacademy.org/profile/{u}', c:'Education', e:'status' },
  { n:'Brilliant', u:'https://brilliant.org/profiles/{u}', c:'Education', e:'status' },
  { n:'Codecademy', u:'https://codecademy.com/profiles/{u}', c:'Education', e:'status' },
  { n:'DataCamp', u:'https://datacamp.com/profile/{u}', c:'Education', e:'status' },
  { n:'Pluralsight', u:'https://pluralsight.com/authors/{u}', c:'Education', e:'status' },
  { n:'LinkedIn Learning', u:'https://linkedin.com/learning/instructor/{u}', c:'Education', e:'status' },

  // HEALTH
  { n:'Strava', u:'https://strava.com/athletes/{u}', c:'Fitness', e:'status' },
  { n:'Fitbit', u:'https://fitbit.com/user/{u}', c:'Fitness', e:'status' },
  { n:'MyFitnessPal', u:'https://myfitnesspal.com/profile/{u}', c:'Fitness', e:'status' },
  { n:'MapMyRun', u:'https://mapmyrun.com/profile/{u}', c:'Fitness', e:'status' },
  { n:'Nike Run Club', u:'https://nike.com/nrc/{u}', c:'Fitness', e:'status' },
  { n:'Peloton', u:'https://onepeloton.com/members/{u}', c:'Fitness', e:'status' },
  { n:'Zwift', u:'https://zwift.com/athlete/{u}', c:'Fitness', e:'status' },
  { n:'AllTrails', u:'https://alltrails.com/members/{u}', c:'Fitness', e:'status' },

  // NEWS / MEDIA
  { n:'Hacker News', u:'https://news.ycombinator.com/user?id={u}', c:'News', e:'status' },
  { n:'Lobsters', u:'https://lobste.rs/u/{u}', c:'News', e:'status' },
  { n:'Digg', u:'https://digg.com/@/{u}', c:'News', e:'status' },
  { n:'Mix', u:'https://mix.com/{u}', c:'News', e:'status' },
  { n:'Flipboard', u:'https://flipboard.com/@{u}', c:'News', e:'status' },
  { n:'Pocket', u:'https://pocket.com/{u}', c:'News', e:'status' },
  { n:'Feedly', u:'https://feedly.com/@{u}', c:'News', e:'status' },
  { n:'Medium Publication', u:'https://{u}.medium.com', c:'News', e:'status' },

  // MISC
  { n:'Gravatar', u:'https://gravatar.com/{u}', c:'Misc', e:'status' },
  { n:'VSCO', u:'https://vsco.co/{u}', c:'Misc', e:'status' },
  { n:'Ello', u:'https://ello.co/{u}', c:'Misc', e:'status' },
  { n:'Cara', u:'https://cara.app/{u}', c:'Misc', e:'status' },
  { n:'Are.na', u:'https://are.na/{u}', c:'Misc', e:'status' },
  { n:'Polywork', u:'https://polywork.com/{u}', c:'Misc', e:'status' },
  { n:'Bento', u:'https://bento.me/{u}', c:'Misc', e:'status' },
  { n:'Taplink', u:'https://taplink.cc/{u}', c:'Misc', e:'status' },
  { n:'Kickstarter', u:'https://kickstarter.com/profile/{u}', c:'Misc', e:'status' },
  { n:'Indiegogo', u:'https://indiegogo.com/individuals/{u}', c:'Misc', e:'status' },
  { n:'GoFundMe', u:'https://gofundme.com/f/{u}', c:'Misc', e:'status' },
  { n:'Change.org', u:'https://change.org/p/{u}', c:'Misc', e:'status' },
  { n:'Petition', u:'https://petition.parliament.uk/petitions/{u}', c:'Misc', e:'status' },
  { n:'Wikipedia', u:'https://en.wikipedia.org/wiki/User:{u}', c:'Misc', e:'status' },
  { n:'Wikidata', u:'https://wikidata.org/wiki/User:{u}', c:'Misc', e:'status' },
  { n:'Wikimedia', u:'https://commons.wikimedia.org/wiki/User:{u}', c:'Misc', e:'status' },
  { n:'Internet Archive', u:'https://archive.org/details/@{u}', c:'Misc', e:'status' },
  { n:'Archive.org', u:'https://archive.org/search?query={u}', c:'Misc', e:'status' },
  { n:'Namechk', u:'https://namechk.com/{u}', c:'Misc', e:'status' },
  { n:'Knowem', u:'https://knowem.com/{u}', c:'Misc', e:'status' },
  { n:'Instant Checkmate', u:'https://instantcheckmate.com/name/{u}', c:'Misc', e:'status' },
  { n:'Spokeo', u:'https://spokeo.com/{u}', c:'Misc', e:'status' },
  { n:'PeekYou', u:'https://peekyou.com/{u}', c:'Misc', e:'status' },
  { n:'Pipl', u:'https://pipl.com/search/?q={u}', c:'Misc', e:'status' },
  { n:'ZabaSearch', u:'https://zabasearch.com/{u}', c:'Misc', e:'status' },
  { n:'Whitepages', u:'https://whitepages.com/name/{u}', c:'Misc', e:'status' },
  { n:'BeenVerified', u:'https://beenverified.com/name/{u}', c:'Misc', e:'status' },
  { n:'IntelTechniques', u:'https://inteltechniques.com/{u}', c:'Misc', e:'status' },
  { n:'OSINT Framework', u:'https://osintframework.com/user/{u}', c:'Misc', e:'status' },
];

export default SITES;
